### ISSUE TITLE
"Global node is not initialized" when read views distributedly (Ray client)

### ISSUE THREAD

**Issue by coufon** [google/space#76]
The error should be because Ray dataset does not support Ray client, as mentioned in https://github.com/ray-project/ray/issues/41333. Working on a fix.

**Comment by coufon** [comment]
Added the solution in https://github.com/google/space/pull/78.

**Comment by Jay-ju** [comment]
@coufon https://github.com/ray-project/ray/issues/49969 How should a scenario like this be solved?
